title: My Site's Title
description: My Site's Description
show_downloads: true
theme: jekyll-theme-midnight
# https://github.com/pages-themes/midnight/
# remote_theme: pages-themes/midnight@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one
